# Documentation - https://github.com/actions/labeler

# General Labels
'Build | Project System':
  - changed-files:
    - any-glob-to-any-file:
      - '.github/*'
      - '.github/**/*'
      - '*.xcconfig'
      - '**/*.xcconfig'
      - '*.xcodeproj/*'
      - '**/*.xcodeproj/*'
      - 'Makefile'
      - '.editorconfig'
      - '.gitignore'

'Dependencies':
  - changed-files:
    - any-glob-to-any-file:
      - 'Dependencies/*'
      - 'Dependencies/**/*'
      - '.gitmodules'

'Documentation':
  - changed-files:
    - any-glob-to-any-file:
      - '*.md'
      - '**/*.md'
      - 'LICENSE'

'GUI/UIKit':
  - changed-files:
    - any-glob-to-any-file:
      - 'zLoader/Features/Views/*'
      - 'zLoader/Features/Views/**/*'
      - 'zLoader/App/App Detail/*.swift'
      - 'zLoader/App/Browse/*.swift'
      - 'zLoader/App/Authentication/*.swift'
      - 'zLoader/App/My Apps/*.swift'
      - 'zLoader/App/News/*.swift'
      - 'zLoader/App/Settings/*.swift'
      - 'zLoader/App/Sources/*.swift'

'Resources | Assets':
  - changed-files:
    - any-glob-to-any-file:
      - 'zLoader/App/Resources/*'
      - 'zLoader/App/Resources/**/*'
      - 'zLoader/App/Base.lproj/*'
      - 'zLoader/App/Base.lproj/**/*'
      - 'SideBackup/Assets.xcassets/*'
      - 'SideBackup/Assets.xcassets/**/*'
      - 'AltWidget/Assets.xcassets/*'
      - 'AltWidget/Assets.xcassets/**/*'

# Tools / Features
'Backup':
  - changed-files:
    - any-glob-to-any-file:
      - 'SideBackup/*'
      - 'SideBackup/**/*'

'Widget':
  - changed-files:
    - any-glob-to-any-file:
      - 'AltWidget/*'
      - 'AltWidget/**/*'

'App Detail':
  - changed-files:
    - any-glob-to-any-file:
      - 'zLoader/App/App Detail/*'
      - 'zLoader/App/App Detail/**/*'

'App IDs':
  - changed-files:
    - any-glob-to-any-file:
      - 'zLoader/App/App IDs/*'
      - 'zLoader/App/App IDs/**/*'

'Authentication':
  - changed-files:
    - any-glob-to-any-file:
      - 'zLoader/App/Authentication/*'
      - 'zLoader/App/Authentication/**/*'

'Browse':
  - changed-files:
    - any-glob-to-any-file:
      - 'zLoader/App/Browse/*'
      - 'zLoader/App/Browse/**/*'

'Managing Apps':
  - changed-files:
    - any-glob-to-any-file:
      - 'zLoader/App/Managing Apps/*'
      - 'zLoader/App/Managing Apps/**/*'

'My Apps':
  - changed-files:
    - any-glob-to-any-file:
      - 'zLoader/App/My Apps/*'
      - 'zLoader/App/My Apps/**/*'

'News':
  - changed-files:
    - any-glob-to-any-file:
      - 'zLoader/App/News/*'
      - 'zLoader/App/News/**/*'

'Settings':
  - changed-files:
    - any-glob-to-any-file:
      - 'zLoader/App/Settings/*'
      - 'zLoader/App/Settings/**/*'

'Sources':
  - changed-files:
    - any-glob-to-any-file:
      - 'zLoader/App/Sources/*'
      - 'zLoader/App/Sources/**/*'

# Core Components
'Core':
  - changed-files:
    - any-glob-to-any-file:
      - 'zLoaderCore/*'
      - 'zLoaderCore/**/*'

'Shared':
  - changed-files:
    - any-glob-to-any-file:
      - 'Shared/*'
      - 'Shared/**/*'

'zLoader':
  - changed-files:
    - any-glob-to-any-file:
      - 'zLoader/Features/*'
      - 'zLoader/Features/**/*'

# Other Core Components
'Operations':
  - changed-files:
    - any-glob-to-any-file:
      - 'zLoader/App/Operations/*'
      - 'zLoader/App/Operations/**/*'

'Intents':
  - changed-files:
    - any-glob-to-any-file:
      - 'zLoader/App/Intents/*'
      - 'zLoader/App/Intents/**/*'

'Permissions':
  - changed-files:
    - any-glob-to-any-file:
      - 'zLoader/App/Permissions/*'
      - 'zLoader/App/Permissions/**/*'

'App Lifecycle':
  - changed-files:
    - any-glob-to-any-file:
      - 'zLoader/App/AppDelegate.swift'
      - 'zLoader/App/SceneDelegate.swift'
      - 'zLoader/App/TabBarController.swift'
      - 'zLoader/App/LaunchViewController.swift'
      - 'zLoader/App/AppConstants.swift'
