//
//  BonjourDiscoveryTypes.swift
//  ZLoader
//
//  Created by Magesh K on 4/7/26.
//  Copyright © 2026 SideStore. All rights reserved.
//

import Foundation

public let commonServiceTypesToBrowse: [String] = [
    "_altserver._tcp.",
    "_remotepairing-pairable-host._tcp.",
    "_remotepairing-manual-pairing._tcp.",
    "_airplay._tcp.",
    "_raop._tcp.",
    "_sftp-ssh._tcp.",
    "_sleep-proxy._udp.",
    "_ssh._tcp.",
    "_apple-mobdev2._tcp.",
    "_asquic._udp.",
    "_companion-link._tcp.",
    "_meshcop._udp.",
    "_remotepairing._tcp.",
    "_rp-tunnel._tcp.",
    "_srpl-tls._tcp.",
    "_trel._udp.",
    "_http._tcp.",
    "_https._tcp.",
    "_smb._tcp.",
    "_afpovertcp._tcp.",
    "_printer._tcp.",
    "_ipp._tcp.",
    "_ipps._tcp.",
    "_scanner._tcp.",
    "_daap._tcp.",
    "_dpap._tcp.",
    "_airport._tcp.",
    "_homekit._tcp.",
    "_hap._tcp.",
    "_touch-able._tcp.",
    "_spotify-connect._tcp.",
    "_googlecast._tcp.",
    "_device-info._tcp.",
    "_workstation._tcp.",
    "_rfb._tcp.",
    "_net-assistant._udp.",
    "_rdlink._tcp.",
    "_stikpairprobe._tcp.",
    "_webdav._tcp.",
    "_webdavs._tcp.",
    "_ftp._tcp.",
    "_telnet._tcp.",
    "_coap._udp.",
    "_coaps._udp.",
    "_mqtt._tcp.",
    "_adb._tcp.",
    "_airdrop._tcp.",
    "_sidecar._tcp.",
    "_sonos._tcp.",
    "_plex._tcp.",
    "_amzn-alexa._tcp.",
    "_home-assistant._tcp.",
    "_rtsp._tcp.",
    "_sip._udp.",
    "_sip._tcp.",
    "_h323._tcp.",
    "_h323._udp.",
    "_ws._tcp.",
    "_wss._tcp.",
    "_remoted._tcp.",
    "_coredevice._tcp.",
    "_appletv-v2._tcp.",
    "_apple-mobdev._tcp.",
    "_jitstreamer._tcp.",
    "_matter._tcp.",
    "_matterc._udp.",
    "_airprint._tcp.",
    "_vnc._tcp."
]

public let commonKnownServiceTypes: [String: String] = [
    "_airplay._tcp.":       "Protocol for streaming of audio/video content",
    "_raop._tcp.":          "Remote Audio Output Protocol (AirTunes)",
    "_sftp-ssh._tcp.":      "Secure File Transfer Protocol over SSH",
    "_sleep-proxy._udp.":   "Sleep Proxy Server",
    "_ssh._tcp.":           "SSH Remote Login Protocol",
    "_http._tcp.":          "World Wide Web (HTTP)",
    "_https._tcp.":         "World Wide Web (HTTPS)",
    "_smb._tcp.":           "SMB File Sharing",
    "_afpovertcp._tcp.":    "Apple Filing Protocol (AFP)",
    "_printer._tcp.":       "Printer",
    "_ipp._tcp.":           "Internet Printing Protocol",
    "_scanner._tcp.":       "Scanner",
    "_ftp._tcp.":           "File Transfer Protocol",
    "_nfs._tcp.":           "Network File System",
    "_daap._tcp.":          "Digital Audio Access Protocol (iTunes)",
    "_dpap._tcp.":          "Digital Photo Access Protocol (iPhoto)",
    "_airport._tcp.":       "AirPort Base Station",
    "_homekit._tcp.":       "HomeKit Accessory",
    "_hap._tcp.":           "HomeKit Accessory Protocol",
    "_companion-link._tcp.": "Companion Link (Apple Watch)",
    "_apple-mobdev2._tcp.":  "Apple Mobile Device v2",
    "_remotepairing._tcp.":  "Remote Pairing",
    "_remotepairing-pairable-host._tcp.": "Remote Pairing (Pairable Host)",
    "_remotepairing-manual-pairing._tcp.": "Remote Pairing (Manual / Apple TV)",
    "_rdlink._tcp.":        "Remote Debug Link",
    "_net-assistant._udp.": "Apple Remote Desktop",
    "_rfb._tcp.":           "Remote Frame Buffer (VNC)",
    "_spotify-connect._tcp.": "Spotify Connect",
    "_googlecast._tcp.":    "Google Cast (Chromecast)",
    "_meshcop._udp.":       "Thread Mesh Commissioning",
    "_asquic._udp.":        "Apple QUIC Service",
    "_rp-tunnel._tcp.":     "Remote Pairing Tunnel",
    "_altserver._tcp.":     "AltServer",
    "_workstation._tcp.":   "Workstation",
    "_device-info._tcp.":   "Device Info",
    "_touch-able._tcp.":    "Remote App (Apple TV Remote)",
    "_srpl-tls._tcp.":      "Spatial Remote Playback Link TLS",
    "_trel._udp.":          "Thread Radio Encapsulation Link",
    "_ipps._tcp.":          "Secure Internet Printing Protocol",
    "_webdav._tcp.":        "Web Distributed Authoring and Versioning (WebDAV)",
    "_webdavs._tcp.":       "Secure WebDAV",
    "_telnet._tcp.":        "Telnet Remote Login Protocol",
    "_coap._udp.":          "Constrained Application Protocol (CoAP)",
    "_coaps._udp.":         "Secure CoAP",
    "_mqtt._tcp.":          "Message Queuing Telemetry Transport (MQTT)",
    "_adb._tcp.":           "Android Debug Bridge (ADB)",
    "_airdrop._tcp.":       "Apple AirDrop",
    "_sidecar._tcp.":       "Apple Sidecar",
    "_sonos._tcp.":         "Sonos Speaker System",
    "_plex._tcp.":          "Plex Media Server",
    "_amzn-alexa._tcp.":    "Amazon Alexa Service",
    "_home-assistant._tcp.": "Home Assistant Smart Home",
    "_rtsp._tcp.":          "Real Time Streaming Protocol (RTSP)",
    "_sip._udp.":           "Session Initiation Protocol (SIP over UDP)",
    "_sip._tcp.":           "Session Initiation Protocol (SIP over TCP)",
    "_h323._tcp.":          "H.323 Video Conferencing (TCP)",
    "_h323._udp.":          "H.323 Video Conferencing (UDP)",
    "_ws._tcp.":            "WebSocket Connection",
    "_wss._tcp.":           "Secure WebSocket Connection",
    "_remoted._tcp.":       "CoreDevice Remote Service Discovery (RSD)",
    "_coredevice._tcp.":    "Apple CoreDevice Debug Service",
    "_appletv-v2._tcp.":    "Apple TV Companion Remote Protocol",
    "_apple-mobdev._tcp.":  "Apple Mobile Device v1 (Wi-Fi Sync)",
    "_jitstreamer._tcp.":   "JitStreamer Service",
    "_matter._tcp.":        "Matter Smart Home Device",
    "_matterc._udp.":       "Matter Device Commissioning",
    "_airprint._tcp.":      "Apple AirPrint",
    "_vnc._tcp.":           "VNC Remote Desktop",
]

public extension String {
    // Strips the network interface scope suffix (e.g. "%en0", "%pdp_ip0") from an IP address or hostname.
    var strippingInterfaceScope: String {
        if let percentIndex = self.firstIndex(of: "%") {
            return String(self[..<percentIndex])
        }
        return self
    }
}

